theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
title: Fateme Nikseresht
logo: photo_2021-10-06_13-49-54.jpg
description: Ph.D. student in Computer Science at University of Virginia
academic_email: fn5an@virginia.edu
linkedin_username: fateme-nikseresht-456951149
github: is\_project\_page:false

plugins:
   - jekyll-seo-tag
   - jekyll-remote-theme
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-gist
#   - jekyll-feed
#   - jemoji
#   - jekyll-include-cache
  
# liquid:
#   error_mode: strict
#   strict_variables: true
#   strict_filters: true


# author:
#   name   : "Fateme Nikseresht"
#   avatar : "photo_2021-10-06_13-49-54.jpg"
#   linkedin: "fateme-nikseresht-456951149"
#   links:
#     - label: "Email"
#       icon: "fas fa-fw fa-envelope-square"
#       url: "fn5an@virginia.edu"
    
